spring:
  cloud:
    gateway:
      discovery:
        locator:
          #开启以服务id去注册中心上获取转发地址
          enabled: true
          ##小写serviceId
          lower-case-service-id: true
      routes:
        - id: portal-service
          #转发地址ser-service,对应eureka的别名
          uri: lb://portal-service
          filters:
            - StripPrefix=1
          predicates:
            - Path=/protal/**
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka