server:
  port: 9999
spring:
  application:
    name: @artifactId@
  cloud:
    gateway:
      discovery:
        locator:
          #开启以服务id去注册中心上获取转发地址
          enabled: true
          ##小写serviceId
          lower-case-service-id: true
      routes:
        - id: user-service
          #转发地址ser-service,对应eureka的别名
          uri: lb://product-service
          filters:
            - StripPrefix=1
            #拦截以/user开头的转发到user-service
          predicates:
            - Path=/user/**

        - id: order-service
          uri: lb://order-service
          filters:
            - StripPrefix=1
          predicates:
            - Path=/order/**

        - id: auth-service
          uri: lb://stock-service
          filters:
            - StripPrefix=1
          predicates:
            - Path=/oauth2/**