server:
  port: 8020
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://47.109.190.221:3306/tb_order?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver





